'''
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


def even_fibonacci_sum(x):
    '''
    Returns the sum of the even fibbonaci numbers below x.
    '''
    fibonacci = [1,2]
    while fibonacci[-2] + fibonacci[-1] < x:
        fibonacci.append(fibonacci[-2] + fibonacci[-1])
    sum = 0
    for i in fibonacci:
        if i % 2 == 0:
            sum += i
    return(sum)

if __name__ == "__main__":
    print(even_fibonacci_sum(4000000))
