;;Problem 2
;;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defun fibonacci (x)
  (let ((fibonacci-list (list 1 1)))
    (loop
      (setq fibonacci-list (append (list (+ (first fibonacci-list) (second fibonacci-list))) fibonacci-list))
      (when (> (car fibonacci-list) x) (return (cdr fibonacci-list))))))

(defun even-sum (lst)
  (cond
    ((NULL lst) 0)
    ((and (ATOM (CAR lst)) (= (mod (CAR lst) 2) 0))
     (+ (even-sum  (CDR lst)) (CAR lst)))
    ((and (ATOM ((CAR lst)) (= (mod (CAR lst) 2) 1)))
     (CDR lst))))

(even-sum (fibonacci 4000000))
